import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <nav className="navbar bg-white ">
          <h1>explore planet</h1>
        </nav>
        <hr />

        <h4 className="text-success mb-3">Input excel file</h4>

        <input
          type="file"
          accept=".csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
        />
        <button className="btn btn-outline-primary" type="button">
          Submit
        </button>
      </main>
    </div>
  );
}
